



version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: curry_postgres
    environment:
      POSTGRES_USER: mac
      POSTGRES_PASSWORD: 
      POSTGRES_DB: bissau_go
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    command: postgres -c 'listen_addresses=*'

volumes:
  postgres_data:





